name: menu
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.2.4
  cupertino_icons: ^1.0.8  # Íconos estilo iOS
  sqflite: ^2.0.2+1  # Para manejar SQLite
  path_provider: ^2.0.11  # Para almacenamiento de archivos

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # Buenas prácticas de código

flutter:
  uses-material-design: true

  assets:
    - assets/images/A1.png  # Aquí va la ruta de tu imagen, asegúrate de que la imagen esté en la carpeta correcta

